#!/bin/bash

# Symlinks to home dir
cd ~
mkdir .dotfiles_old

mv .vimrc .dotfiles_old
ln -s .dotfiles/vimrc .vimrc
mv .vim .dotfiles_old
ln -s .dotfiles/vim .vim

# Install Vundle first
git clone https://github.com/gmarik/Vundle.vim.git .vim/bundle/Vundle.vim

# Install Vundle plugins
vim +PluginInstall +qall

