#!/bin/bash

cd ~

# Backup old files
mkdir .dotfiles_old
mv .vimrc .dotfiles_old
mv .vim .dotfiles_old
mv .zshrc .dotfiles_old

# Clone dotfiles repo
#git clone https://github.com/mjipeo/dotfiles.git .dotfiles
ln -s .dotfiles/vimrc .vimrc
ln -s .dotfiles/vim .vim
ln -s .dotfiles/zshrc .zshrc

# Install dependencies
# TODO: Zsh
# TODO: Ag
#       brew install the_silver_searcher
#       brew install automake pkg-config  pcre
# TODO: Exuberant ctags for Tagbar
#       brew install ctags-exuberant

# Install Vundle first
git clone https://github.com/gmarik/Vundle.vim.git .vim/bundle/Vundle.vim

# Install Vundle plugins
vim +PluginInstall +qall

